FROM ubuntu:15.10
MAINTAINER Patrick van Amstel <patrickvanamstel@gmail.com>

RUN apt-get update && apt-get upgrade

RUN apt-get install -y software-properties-common 
RUN apt-get install -y python-software-properties

