FROM ubuntu:17.10
MAINTAINER Patrick van Amstel <patrickvanamstel@gmail.com>

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y software-properties-common 
RUN apt-get install -y python-software-properties

